# Base image set to the latest Ubuntu version
FROM ubuntu:latest

# Update package lists and perform system upgrade
RUN apt-get update && apt-get upgrade -y

# Command to execute when the container starts, outputs "Hello, World!"
CMD echo "Hello, World!"
